### Teste inicial
GET http://localhost:8082/api/clientes/testeCliente1

### Teste com PathVariable
GET http://localhost:8082/api/clientes/testeCliente2/Diogo Lima Gomes de Oliveira

### Teste com outro nome
GET http://localhost:8082/api/clientes/testeCliente2/Jonas Brothers Band

### Teste com int
GET http://localhost:8082/api/clientes/testeCliente3/21

### Teste com lista de clientes
GET http://localhost:8082/api/clientes/listarClientes

### Criar Cliente
POST http://localhost:8082/api/clientes
Content-Type: application/json

{
  "id": 1,
  "nome": "João da Silva"
}

### Criar Cliente
POST http://localhost:8082/api/clientes/criarClientes
Content-Type: application/json

{
  "id": 3,
  "nome": "Leterino"
}

### Deletar Cliente
DELETE http://localhost:8082/api/clientes/deletarCliente/1

### Alterar Cliente
PUT http://localhost:8082/api/clientes/alerarCliente/1
Content-Type: application/json

{
  "id": 3,
  "nome": "Abiguer"
}
###H2 Get
GET http://localhost:8082/api/clientes

###H2 Post
POST http://localhost:8082/api/clientes
Content-Type: application/json

{
  "nome": "Leterino",
  "endereco": "Colina plana"
}
###H2 Put
PUT http://localhost:8082/api/clientes/5
Content-Type: application/json

{
  "id": 5,
  "nome": "Leterino",
  "endereco": "Colina muito plana mesmo"
}
###H2 Delete
DELETE http://localhost:8082/api/clientes/3